INSERT INTO Judet (numeJudet)
VALUES
    ('Alba'),
    ('Arad'),
    ('Arges'),
    ('Bacau'),
    ('Bihor'),
    ('Bistrita-Nasaud'),
    ('Botosani'),
    ('Braila'),
    ('Brasov'),
    ('Bucuresti'),
    ('Buzau'),
    ('Calarasi'),
    ('Caras-Severin'),
    ('Cluj'),
    ('Constanta'),
    ('Covasna'),
    ('Dambovita'),
    ('Dolj'),
    ('Galati'),
    ('Giurgiu')

INSERT INTO Municipiu (numeMunicipiu, judetID)
VALUES
    ('Alba Iulia', 1),
    ('Arad', 2),
    ('Pitesti', 3),
    ('Bacau', 4),
    ('Oradea', 5),
    ('Bistrita', 6),
    ('Botosani', 7),
    ('Braila', 8),
    ('Brasov', 9),
    ('Bucuresti', 10),
    ('Buzau', 11),
    ('Calarasi', 12),
    ('Resita', 13),
    ('Cluj-Napoca', 14),
    ('Constanta', 15),
    ('Sfantu Gheorghe', 16),
    ('Targoviste', 17),
    ('Craiova', 18),
    ('Galati', 19),
    ('Giurgiu', 20)

INSERT INTO Oras (numeOras, municipiuID)
VALUES
    ('Zlatna', 1),
    ('Arad', 2),
    ('Curtea de Arges', 3),
    ('Bacau', 4),
    ('Beius', 5),
    ('Bistrita', 6),
    ('Botosani', 7),
    ('Braila', 8),
    ('Brasov', 9),
    ('Bucuresti', 10),
    ('Buzau', 11),
    ('Calarasi', 12),
    ('Caransebes', 13),
    ('Cluj-Napoca', 14),
    ('Constanta', 15),
    ('Sfantu Gheorghe', 16),
    ('Targoviste', 17),
    ('Craiova', 18),
    ('Galati', 19),
    ('Giurgiu', 20),
    ('Abrud', 1),
    ('Ineu', 2),
    ('Topoloveni', 3),
    ('Moinesti', 4),
    ('Marghita', 5),
    ('Nasaud', 6),
    ('Saveni', 7),
    ('Faurei', 8),
    ('Codlea', 9),
    ('Pantelimon', 10),
    ('Ramnicu Sarat', 11),
    ('Lehliu Gara', 12),
    ('Moldova Noua', 13),
    ('Dej', 14),
    ('Eforie Nord', 15),
    ('Covasna', 16),
	('Timisoara', 17),
	('Brasov', 18),
	('Constanta', 19),
	('Iasi', 20)

INSERT INTO Tematica (Tematica)
VALUES
	('Art'),
	('Politics'),
	('Sports'),
	('Technology'),
	('Fashion'),
	('Travel'),
	('Food'),
	('Education'),
	('Music'),
	('Entertainment'),
	('Health'),
	('Environment'),
	('Business'),
	('Science'),
	('Religion'),
	('History'),
	('Social issues'),
	('Relationships'),
	('Family'),
	('Celebrity gossip');

INSERT INTO Intrebare (Intrebare, tematicaID)
VALUES
	('What is your favorite type of art?', 1),
	('Do you think art is an important part of society?', 1),
	('What is the most important political issue facing our country today?', 2),
	('How do you feel about the current political climate?', 2),
	('What is your favorite sport to watch?', 3),
	('Do you play any sports?', 3),
	('Do you consider yourself tech-savvy?', 4),
	('What is your favorite piece of technology?', 4),
	('How important is fashion to you?', 5),
	('What is your go-to outfit?', 5),
	('Do you think technology is improving our lives or making them worse?', 4),
	('What is your favorite cuisine?', 7),
	('Should religion play a role in politics?', 2),
	('What is your favorite sport to watch?', 3),
	('Do you believe in climate change?', 12)

INSERT INTO Raspuns (Raspuns, intrebareID, persoanaID)
VALUES
	('Yes, I love to paint and draw', 1),
	('No, I am not interested in art', 1),
	('I prefer classical music', 2),
	('I like to keep up with current political events', 3),
	('I support my local sports team', 4),
	('I think technology is advancing too quickly', 5),
	('I love to try new fashion trends', 6),
	('I enjoy traveling to new places', 7),
	('I love to cook and try new foods', 8),
	('I value education and continue to learn', 9),
	('I like to watch movies and TV shows for entertainment', 10),
	('I prioritize my physical health and well-being', 11),
	('I am concerned about the impact of climate change on the environment', 12),
	('I have experience running my own business', 13),
	('I am interested in science and its advancements', 14),
	('I practice a specific religion', 15),
	('I am fascinated by history and its lessons', 16),
	('I am passionate about social justice issues', 17),
	('I am in a committed relationship', 18),
	('I value spending time with my family', 19);
