use PollDB

INSERT INTO Judet (numeJudet)
VALUES
    ('Alba'),
    ('Arad'),
    ('Arges'),
    ('Bacau'),
    ('Bihor'),
    ('Bistrita-Nasaud'),
    ('Botosani'),
    ('Braila'),
    ('Brasov'),
    ('Bucuresti'),
    ('Buzau'),
    ('Calarasi'),
    ('Caras-Severin'),
    ('Cluj'),
    ('Constanta'),
    ('Covasna'),
    ('Dambovita'),
    ('Dolj'),
    ('Galati'),
    ('Giurgiu')

INSERT INTO Municipiu (numeMunicipiu, judetID)
VALUES
    ('Alba Iulia', 1),
    ('Arad', 2),
    ('Pitesti', 3),
    ('Bacau', 4),
    ('Oradea', 5),
    ('Bistrita', 6),
    ('Botosani', 7),
    ('Braila', 8),
    ('Brasov', 9),
    ('Bucuresti', 10),
    ('Buzau', 11),
    ('Calarasi', 12),
    ('Resita', 13),
    ('Cluj-Napoca', 14),
    ('Constanta', 15),
    ('Sfantu Gheorghe', 16),
    ('Targoviste', 17),
    ('Craiova', 18),
    ('Galati', 19),
    ('Giurgiu', 20)

INSERT INTO Oras (numeOras, municipiuID)
VALUES
    ('Zlatna', 1),
    ('Arad', 2),
    ('Curtea de Arges', 3),
    ('Bacau', 4),
    ('Beius', 5),
    ('Bistrita', 6),
    ('Botosani', 7),
    ('Braila', 8),
    ('Brasov', 9),
    ('Bucuresti', 10),
    ('Buzau', 11),
    ('Calarasi', 12),
    ('Caransebes', 13),
    ('Cluj-Napoca', 14),
    ('Constanta', 15),
    ('Sfantu Gheorghe', 16),
    ('Targoviste', 17),
    ('Craiova', 18),
    ('Galati', 19),
    ('Giurgiu', 20),
    ('Abrud', 1),
    ('Ineu', 2),
    ('Topoloveni', 3),
    ('Moinesti', 4),
    ('Marghita', 5),
    ('Nasaud', 6),
    ('Saveni', 7),
    ('Faurei', 8),
    ('Codlea', 9),
    ('Pantelimon', 10),
    ('Ramnicu Sarat', 11),
    ('Lehliu Gara', 12),
    ('Moldova Noua', 13),
    ('Dej', 14),
    ('Eforie Nord', 15),
    ('Covasna', 16),
	('Timisoara', 17),
	('Brasov', 18),
	('Constanta', 19),
	('Iasi', 20)

INSERT INTO Persoana (Nume, Prenume, sex, studii, email, DataNasterii, judetID, municipiuID, orasID, Casatorit, Divortat, Participant)
VALUES
	('Popescu', 'Ion', 'M', 'Facultate', 'ion.popescu@gmail.com', '01/01/1980', 1, 1, 1, 0, 0, 1),
	('Ionescu', 'Maria', 'F', 'Master', 'maria.ionescu@yahoo.com', '15/02/1990', 2, 2, 2, 1, 0, 1),
	('Popa', 'George', 'M', 'Doctorat', 'george.popa@gmail.com', '20/06/1975', 3, 3, 3, 1, 0, 1),
	('Andrei', 'Alexandra', 'F', 'Facultate', 'alexandra.andrei@gmail.com', '05/09/2000', 4, 4, 4, 0, 0, 1),
	('Gheorghe', 'Marius', 'M', 'Master', 'marius.gheorghe@yahoo.com', '31/12/1985', 5, 5, 5, 1, 1, 1)

INSERT INTO Tematica (Tematica)
VALUES
	('Arta'),
	('Politica'),
	('Sport'),
	('Tehnologie'),
	('Moda'),
	('Calatorii'),
	('Gastronomie'),
	('Educatie'),
	('Muzica'), 
	('Divertisment'), 
	('Sanatate'), 
	('Mediu'), 
	('Afaceri'), 
	('Stiinta'), 
	('Religie');

INSERT INTO Intrebare (Intrebare, tematicaID)
VALUES
	('Care este artistul tau preferat?', 1),
	('Ce opinie ai despre politica actuala?', 2),
	('Care este sportul tau preferat?', 3),
	('Ce gadget tehnologic nu ai putea trai fara?', 4),
	('Ce stil vestimentar preferi?', 5),
	('Care este cea mai frumoasa destinatie de calatorie pe care ai vizitat-o?', 6),
	('Ce fel de mancare preferi?', 7),
	('Ce subiect ti-ar placea sa inveti mai mult despre?', 8),
	('Care este melodia ta preferata?', 9),	
	('Care este filmul sau serialul tau preferat?', 10),
	('Ce ai facut recent pentru a-ti mentine sanatatea?', 11),
	('Ce crezi despre incalzirea globala si schimbarile climatice?', 12),
	('Ai vreo afacere sau idee de afacere pe care ti-ar placea sa o incepi?', 13),
	('Care este cel mai interesant lucru pe care l-ai invatat recent?', 14),
	('Ce inseamnă religia pentru tine?', 15);
	
INSERT INTO Limba (Limba)
VALUES
	('Engleza'), 
	('Franceza'), 
	('Germana'), 
	('Spaniola'), 
	('Italiana'), 
	('Romana'), 
	('Rusa')

INSERT INTO Raspuns (Raspuns, intrebareID, persoanaID, limbaID)
VALUES
	('Michael Jackson', 1, 1, 2),
	('Ed Sheeran', 1, 2, 1),
	('Adele', 1, 3, 5),
	('Queen', 1, 4, 4),
	('Coldplay', 1, 5, 7),
	('Nu sunt interesat de politica', 2, 1, 2),
	('Sunt dezamagit de politica actuala', 2, 2, 1),
	('Cred ca sunt necesare reforme politice majore', 2, 3, 5),
	('Consider ca politica ar trebui sa se concentreze mai mult pe nevoile cetatenilor', 2, 4, 4),
	('Sunt multumit de situatia politica actuala', 2, 5, 7),
	('Fotbal', 3, 1, 2),
	('Tenis', 3, 2, 1),
	('Volei', 3, 3, 5),
	('Ciclism', 3, 4, 4),
	('Inot', 3, 5, 7),
	('Telefonul mobil', 4, 1, 2),
	('Laptopul', 4, 2, 1),
	('Tableta', 4, 3, 5),
	('Smartwatch-ul', 4, 4, 4),
	('Drona', 4, 5, 7),
	('Casual', 5, 1, 2),
	('Elegant', 5, 2, 1),
	('Sport', 5, 3, 5),
	('Hippy', 5, 4, 4),
	('Urban', 5, 5, 7),
	('Toscana, Italia', 6, 1, 2),
	('New York, SUA', 6, 2, 1),
	('Tokyo, Japonia', 6, 3, 5),
	('Bali, Indonezia', 6, 4, 4),
	('Maldivele', 6, 5, 7),
	('Pizza', 7, 1, 2),
	('Sushi', 7, 2, 1),
	('Burger', 7, 3, 5),
	('Paste', 7, 4, 4),
	('Friptura', 7, 5, 7),
	('Istorie', 8, 1, 2),
	('Psihologie', 8, 2, 1),
	('Arta culinara', 8, 3, 5),
	('Programare', 8, 4, 4),
	('Design grafic', 8, 5, 7),
	('Bohemian Rhapsody - Queen', 9, 1, 2),
	('Stairway to Heaven - Led Zeppelin', 9, 2, 1),
	('Smells Like Teen Spirit - Nirvana', 9, 3, 5),
	('Nothing Else Matters - Metallica', 9, 4, 4),
	('November Rain - Guns N Roses', 9, 5, 7),
	('The Godfather', 10, 1, 2),
	('Breaking Bad', 10, 2, 1),
	('Game of Thrones', 10, 3, 5),
	('The Shawshank Redemption', 10, 4, 4),
	('The Big Bang Theory', 10, 5, 7),
	('M-am inscris la un club de fitness', 11, 1, 2),
	('Mananc mai sanatos', 11, 2, 1),
	('Am inceput sa alerg in parc', 11, 3, 5),
	('Fac yoga', 11, 4, 4),
	('Am inceput sa merg la sala de fitness', 11, 5, 7),
	('Este un fenomen real și preocupant', 12, 1, 2),
	('Este o inventie a mass-mediei', 12, 2, 1),
	('Nu cred ca o atat de importanta', 12, 3, 5),
	('Nu am o opinie', 12, 4, 4),
	('Este extrem de important sa atragem atentia aspura acestei probleme', 12, 5, 7)
	
